version: 2
updates:
  - package-ecosystem: "docker"
    directory: /packaging/docker/alpine
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: /packaging/docker/alpine-k8s
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: /packaging/docker/sidecar
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: /packaging/docker/ubuntu-18.04
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: ubuntu
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: /packaging/docker/ubuntu-20.04
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: ubuntu
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: /packaging/docker/ubuntu-22.04
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: ubuntu
        update-types: 
          - "version-update:semver-major"
          - "version-update:semver-minor"
  - package-ecosystem: "docker"
    directory: /.buildkite
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: /
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      otel:
        patterns:
        - go.opentelemetry.io/*
      golang-x:
        patterns:
        - golang.org/x/*
      cloud-providers:
        patterns:
        - github.com/Azure/*
        - github.com/aws/*
        - google.golang.org/*
