version: "3.2"

# This is a docker-compose file designed to be called in macOS and translate through to windows

# Windows docker has some challenges, namely that bind mounts can't be over existing directories and
# symlinks are used, so we need to do create a new gopath and mount it at the root of the gopath. This
# means we count on $GOPATH having a single entry and it being under your macOS user directory. Mine
# is /Users/lachlan/go.

# See https://github.com/docker/compose/issues/5371 and https://github.com/moby/moby/issues/27537#issuecomment-271546031
# for some details of the horrors within

services:
  agent:
    build:
      dockerfile: Dockerfile-windows
      context: .
    working_dir: G:/src/github.com/buildkite/agent
    environment:
      - BUILDKITE_BUILD_NUMBER
      - "BUILDKITE_AGENT_TAGS=queue=default"
      - "BUILDKITE_BUILD_PATH=c:\\buildkite"
      - "GOPATH=G:\\"
    volumes:
      - type: bind
        source: "C:${GOPATH}"
        target: "C:/data"

networks:
  default:
    external:
      name: nat
