version: '2.1'

# This is an override file that Buildkite uses for it's internal docker development
# setup. The buildkite_default network is the network that our other development
# containers run on.
#
# Run with:
# docker-compose -f docker-compose.yml -f docker-compose.bk-dev.yml run --rm agent

services:
  agent:
    command: "buildkite-agent start --endpoint http://agent.buildkite.dev/v3"
    environment:
      BUILDKITE_AGENT_TOKEN: test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: buildkite_default