version: '2.1'

services:
  agent:
    image: golang:1.12
    volumes:
      - ../:/go/src/github.com/buildkite/agent:cached
    working_dir: /go/src/github.com/buildkite/agent
    environment:
      - GOFLAGS=-mod=vendor
      - GO111MODULE=off
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_JOB_ID
      - BUILDKITE_BRANCH
      - "BUILDKITE_AGENT_TAGS=queue=default"
      - "BUILDKITE_BUILD_PATH=/buildkite"
