version: "3.2"

# This is a docker-compose file designed to be called in macOS and translate through to windows

services:
  agent:
    build:
      dockerfile: .buildkite/Dockerfile-windows
      context: ../
    volumes:
      - ../:c:/Users/ContainerAdministrator/go/src/github.com/buildkite/agent
    tty: false
    environment:
      - BUILDKITE_BUILD_NUMBER
      - "BUILDKITE_BUILD_PATH=c:\\buildkite\\builds"
      - BUILDKITE_BRANCH
      - GOFLAGS=-mod=vendor
      - GO111MODULE=off

networks:
  default:
    external:
      name: nat
