version: "3.2"

# This is a docker-compose file designed to be called in macOS and translate through to windows

services:
  agent:
    build:
      dockerfile: .buildkite/Dockerfile-windows
      context: ../
    tty: false
    environment:
      - BUILDKITE_BUILD_NUMBER
      - "BUILDKITE_BUILD_PATH=c:\\buildkite\\builds"
      - GO111MODULE=on

networks:
  default:
    external:
      name: nat
