env:
  DRY_RUN: false # set to true to disable publishing releases

steps:
  - name: ":hammer: :linux:"
    command: ".buildkite/steps/tests.sh"
    artifact_paths: junit-*.xml
    plugins:
      docker-compose#v3.0.0:
        config: .buildkite/docker-compose.yml
        run: agent

  - name: ":hammer: :windows:"
    command: ".buildkite\\steps\\tests.sh"
    artifact_paths: junit-*.xml
    plugins:
      docker-compose#v3.0.0:
        config: .buildkite/docker-compose.windows.yml
        run: agent
        tty: false
        shell: ["bash.exe"]
    agents:
      queue: "windows"

  - wait: ~
    continue_on_failure: true

  - label: ":junit:"
    plugins:
      - junit-annotate#v1.6.0:
          artifacts: junit-*.xml

  - wait

  - name: "Build"
    command: ".buildkite/steps/build-binary.sh windows 386"
    artifact_paths: "pkg/*"
    plugins:
      docker-compose#v3.0.0:
        config: .buildkite/docker-compose.yml
        run: agent

  - wait

  - name: ":hammer: bk cli"
    command: ".buildkite/steps/test-bk.sh"
    soft_fail:
      - exit_status: '*'
    plugins:
      docker-compose#v3.0.0:
        config: .buildkite/docker-compose.yml
        run: agent
        env:
          - BUILDKITE_AGENT_ACCESS_TOKEN
          - BUILDKITE_BUILD_ID
          - BUILDKITE_JOB_ID
        volumes:
          - "/usr/bin/buildkite-agent:/usr/bin/buildkite-agent"

  - wait

  - name: ":mag:"
    command: ".buildkite/steps/extract-agent-version-metadata.sh"

  - wait

  - name: ":docker: alpine build"
    command: ".buildkite/steps/build-docker-image.sh alpine"

  - name: ":docker: ubuntu build"
    command: ".buildkite/steps/build-docker-image.sh ubuntu"

  - name: ":debian: build"
    command: ".buildkite/steps/build-debian-packages.sh"
    artifact_paths: "deb/**/*"
    agents:
      queue: "deploy"

  - name: ":redhat: build"
    command: ".buildkite/steps/build-rpm-packages.sh"
    artifact_paths: "rpm/**/*"
    agents:
      queue: "deploy"

  - name: ":github: :hammer:"
    command: ".buildkite/steps/build-github-release.sh"
    artifact_paths: "releases/**/*"
    plugins:
      docker-compose#v1.8.0:
        config: .buildkite/docker-compose.release.yml
        run: github-release

  - wait

  - name: ":pipeline:"
    command: ".buildkite/steps/upload-release-steps.sh"
