steps:
  - wait

  - name: ":s3: Publish Edge Binaries"
    command: ".buildkite/steps/publish-to-s3.sh"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          propagate-environment: true
          mount-buildkite-agent: true

  - name: ":redhat: Publish Edge RPM Package"
    command: ".buildkite/steps/publish-rpm-package.sh"
    env:
      CODENAME: "experimental"
      RPM_S3_BUCKET: "yum.buildkite.com"
    agents:
      queue: "deploy"
    plugins:
      - docker#v5.8.0:
          image: "buildkite/agent:3.55.0-ubuntu"
          entrypoint: bash
          propagate-environment: true
          mount-buildkite-agent: true
          volumes:
            - "/yum.buildkite.com"

  - name: ":redhat: Publish Edge RPM Package to Packagecloud"
    command: ".buildkite/steps/publish-rpm-packagecloud.sh"
    env:
      REPOSITORY: "buildkite/agent-experimental"
      DISTRO_VERSION: rpm_any/rpm_any
    agents:
      queue: "deploy"
    plugins:
      - docker#v5.8.0:
          image: "public.ecr.aws/docker/library/ruby:3.0"
          entrypoint: bash
          propagate-environment: true
          mount-buildkite-agent: true
    soft_fail: true

  - name: ":debian: Publish Edge Debian Package"
    command: ".buildkite/steps/publish-debian-package.sh"
    env:
      CODENAME: "experimental"
      DEB_S3_BUCKET: "apt.buildkite.com/buildkite-agent"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.7.0:
          login: true
          account-ids: "032379705303"
      - docker#v5.8.0:
          image: "032379705303.dkr.ecr.us-east-1.amazonaws.com/deploytools:2022.07"
          propagate-environment: true
          mount-buildkite-agent: true
          tmpfs:
            - "/root/.gnupg"
    retry:
      automatic:
        - exit_status: 1
          limit: 3

  - name: ":debian: Publish Edge Debian Package to Packagecloud"
    command: ".buildkite/steps/publish-debian-packagecloud.sh"
    env:
      REPOSITORY: "buildkite/agent-experimental"
      DISTRO_VERSION: any/any
    agents:
      queue: "deploy"
    plugins:
      - docker#v5.8.0:
          image: "public.ecr.aws/docker/library/ruby:3.0"
          entrypoint: bash
          propagate-environment: true
          mount-buildkite-agent: true
    soft_fail: true

  - name: ":docker: Publish Edge Docker Images"
    command: ".buildkite/steps/publish-docker-images.sh"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"
    plugins:
      - ecr#v2.7.0:
          login: true
          account-ids: "445615400570"
